for:
  -
    matrix:
      only:
        - job_group: Tests
    build_script:
      - cmd: .\build.cmd Test
      - sh: ./build.cmd Test
  -
    matrix:
      only:
        - job_name: MacOS Tests
    install:
      - sh: |
          wget -q -O /tmp/dotnet-install.sh https://dot.net/v1/dotnet-install.sh
          chmod +x /tmp/dotnet-install.sh
          /tmp/dotnet-install.sh -Version 9.0.101 -InstallDir /usr/share/dotnet
  -
    matrix:
      only:
        - job_name: Ubuntu Tests + Push
    install:
      - sh: |
          wget -q -O /tmp/dotnet-install.sh https://dot.net/v1/dotnet-install.sh
          chmod +x /tmp/dotnet-install.sh
          /tmp/dotnet-install.sh -Version 9.0.101 -InstallDir /usr/share/dotnet
    build_script:
      - cmd: .\build.cmd UploadCodecov PushNuGet PushMyGet
      - sh: ./build.cmd UploadCodecov PushNuGet PushMyGet

artifacts:
  - path: artifacts/*.nupkg

environment:
  MYGET_API_KEY:
    secure: 78qy8e6pKfJlQV7RAG5tJOWegzXpjASkUs3aFdVBoPYA5gi6+mWdjbuAmNa5OQPe
  NUGET_API_KEY:
    secure: 6MkPTvHJIpZhqOH9BCycM4BA++x1SYTINJQ04uR+BxZn2UaUmatB7NkwPCVGBviq
  CODECOV_TOKEN:
    secure: 3FxtGPNTgZyQGToJBaH68/oIjptV79CcViR9mHt2aOKGh3++oKTehBIuPSb7oYCE
  matrix:
    - job_name: Windows Tests
      job_group: Tests
      appveyor_build_worker_image: Visual Studio 2022
    - job_name: MacOS Tests
      job_group: Tests
      appveyor_build_worker_image: macos-sonoma
    - job_name: Ubuntu Tests + Push
      job_depends_on: Tests
      appveyor_build_worker_image: Ubuntu2204
