build_script:
  - cmd: .\build.cmd Test
  - sh: ./build.cmd Test

for:
  -
    matrix:
      only:
        - job_name: Ubuntu Tests + Push
    build_script:
      - cmd: .\build.cmd UploadCodecov PushNuGet PushMyGet
      - sh: ./build.cmd UploadCodecov PushNuGet PushMyGet

artifacts:
  - path: artifacts/*.nupkg

environment:
  MYGET_API_KEY:
    secure: 78qy8e6pKfJlQV7RAG5tJOWegzXpjASkUs3aFdVBoPYA5gi6+mWdjbuAmNa5OQPe
  NUGET_API_KEY:
    secure: 6MkPTvHJIpZhqOH9BCycM4BA++x1SYTINJQ04uR+BxZn2UaUmatB7NkwPCVGBviq
  CODECOV_TOKEN:
    secure: 3FxtGPNTgZyQGToJBaH68/oIjptV79CcViR9mHt2aOKGh3++oKTehBIuPSb7oYCE
  matrix:
    - job_name: Windows Tests
      job_group: Tests
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
    - job_name: MacOS Tests
      job_group: Tests
      APPVEYOR_BUILD_WORKER_IMAGE: macos-sonoma
    - job_name: Ubuntu Tests + Push
      job_depends_on: Tests
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2204
