for:
  -
    matrix:
      only:
        - job_group: Tests
    build_script:
      - cmd: .\build.cmd Test
      - sh: ./build.cmd Test
  -
    matrix:
      only:
        - job_name: Ubuntu Tests + Push
    build_script:
      - cmd: .\build.cmd UploadCodecov PushNuGet PushMyGet
      - sh: ./build.cmd UploadCodecov PushNuGet PushMyGet

artifacts:
  - path: artifacts/*.nupkg

environment:
  MYGET_API_KEY:
    secure: 78qy8e6pKfJlQV7RAG5tJOWegzXpjASkUs3aFdVBoPYA5gi6+mWdjbuAmNa5OQPe
  NUGET_API_KEY:
    secure: 6MkPTvHJIpZhqOH9BCycM4BA++x1SYTINJQ04uR+BxZn2UaUmatB7NkwPCVGBviq
  matrix:
    - job_name: Windows Tests
      job_group: Tests
      appveyor_build_worker_image: Visual Studio 2022
    - job_name: MacOS Tests
      job_group: Tests
      appveyor_build_worker_image: MacOs
    - job_name: Ubuntu Tests + Push
      job_depends_on: Tests
      appveyor_build_worker_image: Ubuntu
